{
  "asi": false,
  "bitwise": true,
  "browser": true,
  "camelcase": true,
  "curly": true,
  "forin": true,
  "immed": true,
  "latedef": "nofunc",
  "maxlen": 80,
  "newcap": true,
  "noarg": true,
  "noempty": true,
  "nonew": true,
  "predef": [
    "$",
    "jQuery",

    "jasmine",
    "beforeEach",
    "describe",
    "expect",
    "it",

    "angular",
    "inject",
    "module"
  ],
  "quotmark": true,
  "trailing": true,
  # set to false because issues with google javascript: google not defined.
  "undef": false,
  # set to false as Javascript called in html.
  "unused": false
}
