language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

notifications:
  slack: cgstudiomap:M6UODn2Bz8HspWEx8UB25Kyb

python:
  - "2.7"

before_script:
#  - sudo psql -c 'create database odoo;' -U travis
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create extension unaccent"

addons:
  postgresql: "9.3"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

virtualenv:
  system_site_packages: true

script:
  - ./main/bin/start_odoo --stop-after-init --workers=0 -d travis -r travis -i main --test-enable
