version: "2"
services:

  pgsql:
    extends:
      file: ../services.yml
      service: arm_pgsql

  cgstudiomap:
    extends:
      file: ../services.yml
      service: arm_odoo
    depends_on:
      - pgsql
    links:
      - "pgsql:pgsql-server"
    command: /opt/cgstudiomap/parts/odoo/openerp-server -c /opt/cgstudiomap/etc/odoo.cfg --unaccent
